name: meu_servidor
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

  shelf: ^1.4.1
  shelf_router: ^1.1.4
  sqflite_common_ffi: ^2.3.2
  path: ^1.8.3

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  flutter_lints: ^2.0.3
